name: sign_speak_mob_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  
  # Camera
  camera: ^0.11.0+2
  
  # MediaPipe Hand Landmarker (21 points)
  hand_landmarker: ^2.2.0
  
  # HTTP Client
  dio: ^5.7.0
  
  # State Management
  provider: ^6.1.2
  
  # Permissions
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
